### PR TITLE
redo buffer completion

### PR DESCRIPTION
**Pull request by prabirshrestha**
redo and simplify buffer completion

### CODE REVIEW

**Comment by amadeus** [comment]
Any thoughts on when this might land? I've been using a fork that I sorta hacked a bit, but would prefer it to be more officially more performant - especially on larger files.

**Comment by prabirshrestha** [comment]
@amadeus I usually don't use buffer completion but has this PR been working better for you then what is in master? Do you also have more patches on it? If so I can try this PR a bit more and then merge in. Let me know your thoughts.

**Comment by amadeus** [comment]
I've been using it and it appears to work pretty well!

**Comment by prabirshrestha** [comment]
merged.

**Pull request merged**
